AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stripe API Example
Resources:
  jsoap:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: Handler::handleRequest
      CodeUri: ./target/jsoap-api-1.0-SNAPSHOT.jar
      Timeout: 30